%% General analysis of load case 1 on the horizontal stabiliser
clear
clc
close all

%% Enter geometry of tailplane horizontal stabiliser

% rootChordLen - root chord length [m]
% tipChordLen - tip chord length [m]
% wingSemiSpan - wing semi-span [m]
% takeOffWeight - Take-off weight of entire aircraft [N]
% N - Number of stations [-]
% n - Load factor [-]
% fuelTankLen - Length of fuel tank wrt half span [m]

rootChordLen = 3.62;
tipChordLen = 1.45;
aspectRatio = 4;
MACtailPlane = 2.54;
wingSemiSpan = aspectRatio*MACtailPlane/2;
horizontalStabilizerWeight = 0.02 * 78*10^3 * 9.81; % get from AVD report
N = 100; % according to lecturer 
n = 1.5*2.5;

%% Enter operating conditions and pitch aerodyamic moment
Cm0TailPlane = 1.1; % pitch aerodynamic moment from airofoil data
cruiseVelocity = 232.78;
rho = 1.1; % at altitude 37000 ft

%% Obtain lift generated by tailplane
% by considering bending moments around the cg of plane
MACWing = 4.85;
Sref = 6.89*36.41^2;
momentArmTailPlane = 25;
momentArmWing = 3; %xcg-xac
CM0Wing = 1.1;
takeOffWeight = 78*10^3 * 9.81; % get from AVD report
% this gets it for half the entire horizontal stabilizer
horizontalStabilizerLift = 0.5 * (1/momentArmTailPlane) * ...
    (-0.5*rho*cruiseVelocity^2*Sref*MACWing*CM0Wing + n*takeOffWeight*momentArmWing);
%% Function call to get shear forces and bending moments
[x, chord, distLift, distWeightWing, shearForceWing, bendingMomentWing] = ...
    horizontal_stabilizer_load(rootChordLen, tipChordLen , wingSemiSpan , ...
    horizontalStabilizerLift,horizontalStabilizerWeight, N , n);

flexAxis = 0.45*chord; % Flex axis is 25 to 65 of chord
ac = 0.25*chord; % aerodynamic center
a = flexAxis - ac; % distence between the flex axis and AC
cgWing = 0.55*chord;
b = cgWing - flexAxis; % difference between cg with respect to chord of wing and FA

% load distributions
distLoad = distLift+distWeightWing;

figure;
hold on
plot(x,distLift,'b') % lift
plot(x,distWeightWing,'r') % self weight
plot(x,distLoad,'k') % total load

hold off

% moment distribution
figure;
plot(x,bendingMomentWing,'k') % all


% shear force:
figure;
plot(x, shearForceWing,'k')

M_0 = 0.5*rho*cruiseVelocity^2.*chord.^2*Cm0TailPlane;
T = distLift.*a*wingSemiSpan+(distLoad-distLift).*b*wingSemiSpan-M_0;

figure;
hold on
plot(x,T) % torque along span
hold off



